-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table ingredientes (
  id                            bigint generated by default as identity not null,
  nombre_ig                     varchar(255) not null,
  descripcion                   varchar(1000) not null,
  cocinero                      varchar(255) not null,
  receta_id                     bigint,
  constraint pk_ingredientes primary key (id)
);

create table receta (
  id                            bigint generated by default as identity not null,
  nombre                        varchar(255) not null,
  tipo_comida                   varchar(255) not null,
  imagen                        varchar(999999),
  ingredientes_descrip_id       bigint,
  constraint uq_receta_ingredientes_descrip_id unique (ingredientes_descrip_id),
  constraint pk_receta primary key (id)
);

create table receta_ingredientes (
  receta_id                     bigint not null,
  ingredientes_id               bigint not null,
  constraint pk_receta_ingredientes primary key (receta_id,ingredientes_id)
);

-- foreign keys and indices
create index ix_ingredientes_receta_id on ingredientes (receta_id);
alter table ingredientes add constraint fk_ingredientes_receta_id foreign key (receta_id) references receta (id) on delete restrict on update restrict;

alter table receta add constraint fk_receta_ingredientes_descrip_id foreign key (ingredientes_descrip_id) references ingredientes (id) on delete restrict on update restrict;

create index ix_receta_ingredientes_receta on receta_ingredientes (receta_id);
alter table receta_ingredientes add constraint fk_receta_ingredientes_receta foreign key (receta_id) references receta (id) on delete restrict on update restrict;

create index ix_receta_ingredientes_ingredientes on receta_ingredientes (ingredientes_id);
alter table receta_ingredientes add constraint fk_receta_ingredientes_ingredientes foreign key (ingredientes_id) references ingredientes (id) on delete restrict on update restrict;


-- !Downs

-- drop all foreign keys
alter table ingredientes drop constraint if exists fk_ingredientes_receta_id;
drop index if exists ix_ingredientes_receta_id;

alter table receta drop constraint if exists fk_receta_ingredientes_descrip_id;

alter table receta_ingredientes drop constraint if exists fk_receta_ingredientes_receta;
drop index if exists ix_receta_ingredientes_receta;

alter table receta_ingredientes drop constraint if exists fk_receta_ingredientes_ingredientes;
drop index if exists ix_receta_ingredientes_ingredientes;

-- drop all
drop table if exists ingredientes;

drop table if exists receta;

drop table if exists receta_ingredientes;

